### ISSUE TITLE
it's okay

### ISSUE THREAD

**Issue by blueghostvivid** [alyrezo/for-test#1]
is it okay or not??!
try run it
###  hehe
_i am not bot bro_
`py just for test.py`
@alyrezo 
tnk you for reply ❤😉

**Comment by alyrezo** [comment]
hey @blueghostvivid 
your welcome for about that
if you have linux, so go to **remove** it now!!!! 😁
your test is amazing!
#  #haha

**Comment by blueghostvivid** [comment]
haha

**Comment by alyrezo** [comment]
okay
